"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['maintest.py']
DATA_FILES = [
	('img', ['img/wp_emboss.png']
)]
OPTIONS = { 'iconfile':'img/wavico.icns'}

setup(
    app=APP,
    name='WavPatcher',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
